"""initial schema with phase10

Revision ID: 372b8a8ff180
Revises: 
Create Date: 2026-08-25 09:20:12.105458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '372b8a8ff180'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('webhook_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.String(length=128), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processing_status', sa.String(length=32), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webhook_events_event_id'), 'webhook_events', ['event_id'], unique=True)
    op.create_index(op.f('ix_webhook_events_event_type'), 'webhook_events', ['event_type'], unique=False)
    op.create_table('merchant_accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('business_name', sa.String(length=255), nullable=False),
    sa.Column('razorpay_key_id', sa.String(length=64), nullable=False),
    sa.Column('is_test_mode', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bank_transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('merchant_account_id', sa.UUID(), nullable=False),
    sa.Column('import_batch_id', sa.UUID(), nullable=False),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('reference_id', sa.String(length=128), nullable=True),
    sa.Column('utr', sa.String(length=64), nullable=True),
    sa.Column('credit', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('debit', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('balance', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('row_hash', sa.String(length=64), nullable=False),
    sa.Column('is_duplicate', sa.Boolean(), nullable=False),
    sa.Column('raw_row', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['merchant_account_id'], ['merchant_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bank_transactions_import_batch_id'), 'bank_transactions', ['import_batch_id'], unique=False)
    op.create_index(op.f('ix_bank_transactions_reference_id'), 'bank_transactions', ['reference_id'], unique=False)
    op.create_index(op.f('ix_bank_transactions_row_hash'), 'bank_transactions', ['row_hash'], unique=False)
    op.create_index(op.f('ix_bank_transactions_transaction_date'), 'bank_transactions', ['transaction_date'], unique=False)
    op.create_index(op.f('ix_bank_transactions_utr'), 'bank_transactions', ['utr'], unique=False)
    op.create_table('razorpay_orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('merchant_account_id', sa.UUID(), nullable=False),
    sa.Column('razorpay_order_id', sa.String(length=64), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('receipt', sa.String(length=128), nullable=True),
    sa.Column('order_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('raw_payload', sa.JSON(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['merchant_account_id'], ['merchant_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_razorpay_orders_order_date'), 'razorpay_orders', ['order_date'], unique=False)
    op.create_index(op.f('ix_razorpay_orders_razorpay_order_id'), 'razorpay_orders', ['razorpay_order_id'], unique=True)
    op.create_table('razorpay_payments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('merchant_account_id', sa.UUID(), nullable=False),
    sa.Column('razorpay_payment_id', sa.String(length=64), nullable=False),
    sa.Column('order_id', sa.String(length=64), nullable=True),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('method', sa.String(length=32), nullable=True),
    sa.Column('fee', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('tax', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('payment_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('raw_payload', sa.JSON(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['merchant_account_id'], ['merchant_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_payment_order', 'razorpay_payments', ['order_id'], unique=False)
    op.create_index(op.f('ix_razorpay_payments_order_id'), 'razorpay_payments', ['order_id'], unique=False)
    op.create_index(op.f('ix_razorpay_payments_payment_date'), 'razorpay_payments', ['payment_date'], unique=False)
    op.create_index(op.f('ix_razorpay_payments_razorpay_payment_id'), 'razorpay_payments', ['razorpay_payment_id'], unique=True)
    op.create_table('razorpay_refunds',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('merchant_account_id', sa.UUID(), nullable=False),
    sa.Column('razorpay_refund_id', sa.String(length=64), nullable=False),
    sa.Column('razorpay_payment_id', sa.String(length=64), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('refund_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('raw_payload', sa.JSON(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['merchant_account_id'], ['merchant_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_razorpay_refunds_razorpay_payment_id'), 'razorpay_refunds', ['razorpay_payment_id'], unique=False)
    op.create_index(op.f('ix_razorpay_refunds_razorpay_refund_id'), 'razorpay_refunds', ['razorpay_refund_id'], unique=True)
    op.create_index(op.f('ix_razorpay_refunds_refund_date'), 'razorpay_refunds', ['refund_date'], unique=False)
    op.create_table('razorpay_settlements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('merchant_account_id', sa.UUID(), nullable=False),
    sa.Column('razorpay_settlement_id', sa.String(length=64), nullable=False),
    sa.Column('utr', sa.String(length=64), nullable=True),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('fees', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('tax', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('settlement_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('raw_payload', sa.JSON(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['merchant_account_id'], ['merchant_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_razorpay_settlements_razorpay_settlement_id'), 'razorpay_settlements', ['razorpay_settlement_id'], unique=True)
    op.create_index(op.f('ix_razorpay_settlements_settlement_date'), 'razorpay_settlements', ['settlement_date'], unique=False)
    op.create_index(op.f('ix_razorpay_settlements_utr'), 'razorpay_settlements', ['utr'], unique=False)
    op.create_table('reconciliation_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('merchant_account_id', sa.UUID(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_transactions', sa.Integer(), nullable=False),
    sa.Column('matched_count', sa.Integer(), nullable=False),
    sa.Column('explained_count', sa.Integer(), nullable=False),
    sa.Column('needs_review_count', sa.Integer(), nullable=False),
    sa.Column('failed_count', sa.Integer(), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('matched_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('unresolved_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('match_rate', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['merchant_account_id'], ['merchant_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reconciliation_cases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('merchant_account_id', sa.UUID(), nullable=False),
    sa.Column('razorpay_payment_id', sa.String(length=64), nullable=True),
    sa.Column('razorpay_settlement_id', sa.String(length=64), nullable=True),
    sa.Column('bank_transaction_id', sa.UUID(), nullable=True),
    sa.Column('expected_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('actual_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('difference', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('match_rule', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['bank_transaction_id'], ['bank_transactions.id'], ),
    sa.ForeignKeyConstraint(['merchant_account_id'], ['merchant_accounts.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['reconciliation_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reconciliation_cases_razorpay_payment_id'), 'reconciliation_cases', ['razorpay_payment_id'], unique=False)
    op.create_index(op.f('ix_reconciliation_cases_razorpay_settlement_id'), 'reconciliation_cases', ['razorpay_settlement_id'], unique=False)
    op.create_index(op.f('ix_reconciliation_cases_status'), 'reconciliation_cases', ['status'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=True),
    sa.Column('actor_type', sa.String(length=16), nullable=False),
    sa.Column('actor_id', sa.String(length=128), nullable=True),
    sa.Column('action', sa.String(length=128), nullable=False),
    sa.Column('previous_state', sa.JSON(), nullable=True),
    sa.Column('new_state', sa.JSON(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['reconciliation_cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_case_id'), 'audit_logs', ['case_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_table('investigations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('classification', sa.String(length=32), nullable=False),
    sa.Column('root_cause', sa.String(length=64), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('recommended_action', sa.Text(), nullable=False),
    sa.Column('requires_human_review', sa.Boolean(), nullable=False),
    sa.Column('ai_model', sa.String(length=64), nullable=False),
    sa.Column('raw_ai_response', sa.JSON(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('human_decision', sa.String(length=32), nullable=True),
    sa.Column('human_decided_by', sa.UUID(), nullable=True),
    sa.Column('human_decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('human_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['reconciliation_cases.id'], ),
    sa.ForeignKeyConstraint(['human_decided_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_investigations_case_id'), 'investigations', ['case_id'], unique=False)
    op.create_table('investigation_evidence',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('investigation_id', sa.UUID(), nullable=False),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('source_id', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('data_snapshot', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_investigation_evidence_investigation_id'), 'investigation_evidence', ['investigation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_investigation_evidence_investigation_id'), table_name='investigation_evidence')
    op.drop_table('investigation_evidence')
    op.drop_index(op.f('ix_investigations_case_id'), table_name='investigations')
    op.drop_table('investigations')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_case_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_reconciliation_cases_status'), table_name='reconciliation_cases')
    op.drop_index(op.f('ix_reconciliation_cases_razorpay_settlement_id'), table_name='reconciliation_cases')
    op.drop_index(op.f('ix_reconciliation_cases_razorpay_payment_id'), table_name='reconciliation_cases')
    op.drop_table('reconciliation_cases')
    op.drop_table('reconciliation_runs')
    op.drop_index(op.f('ix_razorpay_settlements_utr'), table_name='razorpay_settlements')
    op.drop_index(op.f('ix_razorpay_settlements_settlement_date'), table_name='razorpay_settlements')
    op.drop_index(op.f('ix_razorpay_settlements_razorpay_settlement_id'), table_name='razorpay_settlements')
    op.drop_table('razorpay_settlements')
    op.drop_index(op.f('ix_razorpay_refunds_refund_date'), table_name='razorpay_refunds')
    op.drop_index(op.f('ix_razorpay_refunds_razorpay_refund_id'), table_name='razorpay_refunds')
    op.drop_index(op.f('ix_razorpay_refunds_razorpay_payment_id'), table_name='razorpay_refunds')
    op.drop_table('razorpay_refunds')
    op.drop_index(op.f('ix_razorpay_payments_razorpay_payment_id'), table_name='razorpay_payments')
    op.drop_index(op.f('ix_razorpay_payments_payment_date'), table_name='razorpay_payments')
    op.drop_index(op.f('ix_razorpay_payments_order_id'), table_name='razorpay_payments')
    op.drop_index('ix_payment_order', table_name='razorpay_payments')
    op.drop_table('razorpay_payments')
    op.drop_index(op.f('ix_razorpay_orders_razorpay_order_id'), table_name='razorpay_orders')
    op.drop_index(op.f('ix_razorpay_orders_order_date'), table_name='razorpay_orders')
    op.drop_table('razorpay_orders')
    op.drop_index(op.f('ix_bank_transactions_utr'), table_name='bank_transactions')
    op.drop_index(op.f('ix_bank_transactions_transaction_date'), table_name='bank_transactions')
    op.drop_index(op.f('ix_bank_transactions_row_hash'), table_name='bank_transactions')
    op.drop_index(op.f('ix_bank_transactions_reference_id'), table_name='bank_transactions')
    op.drop_index(op.f('ix_bank_transactions_import_batch_id'), table_name='bank_transactions')
    op.drop_table('bank_transactions')
    op.drop_table('merchant_accounts')
    op.drop_index(op.f('ix_webhook_events_event_type'), table_name='webhook_events')
    op.drop_index(op.f('ix_webhook_events_event_id'), table_name='webhook_events')
    op.drop_table('webhook_events')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
